Cài đặt chung





In [ ]:
'''from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"   '''
#dòng lệnh để in ra nhiều giá trị trong jupyter

In [4]:
import numpy as np
#import package numpy

# Khai báo và sử dụng mảng                    
                                

### Creating Numpy array from Scratch

zeros, ones, full, arange, linspace 

Bấm shift Tab để hiện ra các thuộc tính của hàm

In [48]:
np.array([1, 2, 3, 4], ndmin=5)
#khởi tạo mảng với ndmin đa chiều

array([[[[[1, 2, 3, 4]]]]])

In [49]:
'''ma trận 2 chiều'''
b=np.array([[1,2,3,4,5],
            [2,3,4,5,6]])

###### tạo mảng đặc biệt

In [44]:
np.zeros([2,4],dtype= int)
#tạo mảng với shape và kiểu dữ liệu có giá trị mặc định 
#là 0

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [53]:
np.ones([2,3],dtype= float)
#tạo mảng với shape và kiểu dữ liệu có giá trị mặc định 
#là 1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
np.arange(0,20,2)
#tạo mảng với dãy giá trị có điểm đầu, cuối, step

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [58]:
np.full((3,5),6.9,dtype=float)
#tạo mảng theo shape với giá trị cho trước, 
#có thể định kiểu dữ liệu

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [43]:
np.linspace(1,2,11)
# tạo mảng từ start đến end 
# với số space cho trước là số element trong khoảng

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [16]:
np.eye(3, dtype= float)
# tạo một ma trận đơn vị vuông

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.diag([1,2,3,4,5])
# tạo một ma trận đường chéo với đường chéo nhập vào

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

###### tạo mảng với với chế độ copy và view

In [60]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = arr.copy()# chế độ copy mọi thay đổi ở bản copy ko ảnh hưởng đến dữ liệu gốc
y = arr.view()# chế độ view mọi thay đổi ở bản view ảnh hưởng đến dữ liệu gốc

print(x.base)# base trả về chủ sở hữu của đối tượng
print(y.base)# ví dụ chủ của view() là đối tượng gốc, chủ của copy() là none(hay là chính nó)
            


None
[1 2 3 4 5 6 7 8]


###### tạo một mảng mới copy từ mảng ban đầu với data type khác

In [47]:
a=np.array([1, 2, 3, 4], ndmin=5)
b=a.astype(dtype='S')
b
'''
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
'''

'\ni - integer\nb - boolean\nu - unsigned integer\nf - float\nc - complex float\nm - timedelta\nM - datetime\nO - object\nS - string\nU - unicode string\nV - fixed chunk of memory for other type ( void )\n'

#####  các hàm thao tác với mảng

In [47]:
# a= np.array([1,2,3,4,5])
print(a.ndim)#lấy số chiều của mảng
a[1]

1


2

In [50]:
print(b.shape)# với mảng 2 chiều shape xuất ra kích thước của ma trận


(2, 5)


In [37]:
len(b[0])# lấy số phần tử của 1 mảng

5

In [40]:
b.size # lấy số element trong 1 mảng(chú ý trong mảng 2 chiều)

10

In [35]:
type(a) #kiểu dữ liệu của a

numpy.ndarray

In [33]:
a.dtype# lấy kiểu dữ liệu trong 1 mảng

dtype('int32')

## random

In [5]:
np.random.random((4,4))
#trả về giá trị ngẫu nhiên tỏng khoảng [0,1) 
#theo size cho trước

array([[0.13022717, 0.47598403, 0.75578242, 0.84117836],
       [0.45208999, 0.72792482, 0.63167667, 0.76903928],
       [0.52288808, 0.46749282, 0.37152897, 0.42459159],
       [0.26767822, 0.55962226, 0.77287146, 0.85427657]])

In [18]:
np.random.seed(0) 
#khoá random để các ma trận đưa ra giá trị cố định
a=np.random.random((4,4))
a

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

## có 2 cách truy nhập phần tử mảng:
### - a[0][0] : như code bt
### - a[0,0]  : như viết giấy

In [21]:
a[0:2,1:3]
# truy cập đến hàng 0->1 của cột 1->3

array([[0.71518937, 0.60276338],
       [0.64589411, 0.43758721]])

## đọc mảng từ file txt

In [26]:
a= np.loadtxt('test.txt',dtype=int, delimiter=' ')
a

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 5],
       [3, 4, 5, 6, 7]])

## các hàm thao tác có tác dụng toàn mảng
##### arr.max() hoặc np.max(arr): Lấy giá trị lớn nhất của mảng arr.
##### arr.min() hoặc np.min(arr): Lấy giá trị nhỏ nhất của mảng arr.

##### arr.sum() hoặc np.sum(arr): Tổng tất cả các phần tử trong mảng arr.
##### arr.mean() hoặc np.mean(arr): Trung bình cộng của tất cả các phần tử trong mảng arr.
##### np.median(arr): Trả về giá trị trung vị của mảng arr.

## Các toán tử với mảng như phép tính với ma trận

In [31]:
A = np.array([[1, 3, 4], [-2, 6, 0], [-5, 7, 2]])
B = np.array([[2, 3, 4], [-1, -2, -3], [0, 4, -4]])
A*B

array([[  2,   9,  16],
       [  2, -12,   0],
       [  0,  28,  -8]])

## chuyển ma trận chuyển vị

In [47]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A.T
# cách 2
np.transpose(A)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## định thức của ma trận

In [36]:
np.linalg.det(A)

6.66133814775094e-16

### rank của ma trận

In [48]:
np.linalg.matrix_rank(A)

2

### Vết của ma trận: Tổng đường chéo chính

In [49]:
print(np.trace(A))
print(A.trace())

15
15


### Đối với chuẩn hàng, ta dùng câu lệnh như sau:

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(np.linalg.norm(A, ord=np.inf))
Kết quả thu được là 33.0

### Đối với chuẩn cột, ta dùng câu lệnh sau:

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(np.linalg.norm(A, ord=1))
Kết quả trả về là 30.0

### Đối với chuẩn Frobenius, ta tính theo cách như sau:

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(np.linalg.norm(A))
### Ta thử dùng công thức tính theo vết ma trận để tính chuẩn Frobenius như nào nhé:

import math as mt

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(mt.sqrt(np.trace(A.T @ A)))

## ma trận nghịch đảo

In [61]:
np.linalg.inv(A)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

## reshape
-điều kiện: 2 array có số element phù hợp

-mảng được tạo ra từ reshape là 1 view()

In [72]:
a=np.array([1,2,3,4,5,6,7,8])
a.reshape(2,4) #  chuyển từ mảng 1D sang 2D có kích thước 3x3


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
a.reshape(2,2,-1) # tham số -1 : numpy tự tính tham số để thay vào reshape 
#note: chỉ có thể có duy nhất 1 tham số -1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [76]:
a.reshape(-1) #chuyển từ mảng 2D 3D về 1D

array([1, 2, 3, 4, 5, 6, 7, 8])

### dùng hamg nditer để duyệt mảng qua từng phần tử 1 (tương tự iter trong core basic)

In [3]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


### duyệt mảng với kiểu dữ liệu khác
#### Note: hàm nditer với tham số op_dtypes tạo ra một bộ nhớ đệm như 1 bản copy nhưng k lưu trữ 


In [4]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


### nối mảng

In [12]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [16]:
arr1 = np.array([[1, 2], 
                 [3, 4]])

arr2 = np.array([[5, 6], 
                 [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### cắt mảng

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [30]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)
print( newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


### tìm kiếm phầnn tử trong mảng

In [33]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)
# tìm kiếm

(array([3, 5, 6], dtype=int32),)


In [40]:
#tìm kiếm theo binary sort
arr = np.array([6, 7,7, 8, 9])

x = np.searchsorted(arr, 7)
# trả về 1 giá trị mặc định là tìm kiếm từ trái sang
# muốn tìm từ phải sang thêm thuộc tính side='right'
x = np.searchsorted(arr, 7,side='right')
print(x)

3


### lọc mảng
#### dùng mảg chứa boolearn 
true loại
false giữ lại

In [43]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]
print(newarr)

[41 43]


In [44]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


### shuffle(xáo trộn ma trận)
#### Note: Thay đổi trực tiếp mảng ban đầu

In [7]:

arr = np.array([1, 2, 3, 4, 5])

np.random.shuffle(arr)
print(arr)

[4 5 2 3 1]


### xáo trộn mảng giữ nguyên mảng ban đầu

In [9]:
arr = np.array([1, 2, 3, 4, 5])

print(np.random.permutation(arr))

[2 3 1 5 4]
